repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.9.1"
    hooks:
      - id: check-github-workflows
        require_serial: true
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
      - id: check-manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.31.0"
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/psf/black
    rev: "21.12b0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.930"
    hooks:
      - id: mypy
        args: [ ]
        exclude: ^(docs/|setup.py$)
        additional_dependencies:
          - pytest
